#!/bin/bash
NAME='\033[1;34m'
ADR='\033[0;33m'
NC='\033[0;0m'
TITLE='\033[1;32m'
NUM='\033[1;36m'
ALERT='\033[1;31m'
LPURP='\033[1;35m'
printf "${TITLE}Do you want to recover your DNS settings?${NC}\n${LPURP}Y or N${NC}\n"
read x 
if [[ "$x" == "Y" || "$x" == "y" ]]; then
printf "${ADR}Recovering...${NC}\n"
sudo chattr -i /etc/resolv.conf
sudo cp /etc/resolv.conf.backup /etc/resolv.conf
sudo chattr +i /etc/resolv.conf
sudo systemctl restart NetworkManager
elif [[ "$x" == "N" || "$x" == "n" ]]; then
printf "${ALERT}Exiting...${NC}\n"
else 
printf "${ALERT}Oops, something went wrong.${NC}\n"
fi